import type { EditorThemeClasses } from "lexical";

const theme: EditorThemeClasses = {
  ltr: "ltr",
  rtl: "rtl",
  placeholder: "editor-placeholder",
  paragraph: "editor-paragraph",
  quote: "editor-quote",
  heading: {
    h1: "editor-heading-h1",
    h2: "editor-heading-h2",
    h3: "editor-heading-h3",
    h4: "editor-heading-h4",
    h5: "editor-heading-h5",
  },
  list: {
    nested: {
      listitem: "editor-nested-listitem",
    },
    ol: "editor-list-ol",
    ul: "editor-list-ul",
    listitem: "editor-listitem",
  },
  image: "editor-image",
  link: "editor-link",
  text: {
    bold: "editor-text-bold",
    italic: "editor-text-italic",
    overflow: "editor-text-overflow",
    hashtag: "editor-text-hashtag",
    underline: "editor-text-underline",
    strikethrough: "editor-text-strikethrough",
    underlineStrikethrough: "editor-text-underlineStrikethrough",
    code: "editor-text-code",
  },
  code: "editor-code",
  codeHighlight: {
    atrule: "editor-tokenAtrule",
    attr: "editor-tokenAttr",
    boolean: "editor-tokenProperty",
    punctuation: "editor-tokenPunctuation",
    tag: "editor-tokenTag",
    tagLabel: "editor-tokenTag",
    operator: "editor-tokenOperator",
    prolog: "editor-tokenProlog",
    comment: "editor-tokenComment",
    string: "editor-tokenString",
    variable: "editor-tokenVariable",
    keyword: "editor-tokenKeyword",
    function: "editor-tokenFunction",
    selector: "editor-tokenSelector",
    regex: "editor-tokenVariable",
    number: "editor-tokenProperty",
    char: "editor-tokenProperty",
    symbol: "editor-tokenProperty",
    namespace: "editor-tokenProperty",
    entity: "editor-tokenOperator",
    constant: "editor-tokenProperty",
    url: "editor-tokenOperator",
    important: "editor-tokenVariable",
    bold: "editor-tokenVariable",
    italic: "editor-tokenVariable",
    namespaceHighlight: "editor-tokenVariable",
    deleted: "editor-tokenProperty",
    inserted: "editor-tokenSelector",
  },
};

export default theme;
